import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Hero from "../components/Hero";
import BackgroundAnimation from "@/components/BackgroundAnimation";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} font-light antialiased grid grid-cols-12 gap-6 col-span-full bg-gray-50 text-gray-900`}
      >
        {/* <div className="fixed -z-20 top-0 left-0 h-screen w-full bg-linear-to-b from-gray-100 via-lime-100 to-lime-200">
          <BackgroundAnimation />
        </div> */}
        <main className="grid grid-cols-subgrid col-span-full backdrop-blur-xs">
          <Header /> 
          {children}
        </main>
      </body>
    </html>
  );
}
